### ISSUE TITLE
MS SQL Server - support for case-sensitive database object names

### ISSUE THREAD

**Issue by javornikolov** [dbfit/dbfit#348]
This originally emerged on the [DbFit mailing list](https://groups.google.com/d/msg/dbfit/6pLuUl1KFGM/dFUzDM2EIVEJ).

Seems DbFit is currently unable to handle certain operations when the underlying database objects are configured as case-sensitive.

**Comment by MMatten** [comment]
I'd like to pick this one up to resolve, via a PR, it as the forum post came from a user at my workplace.

I've read through the forum post and I've done some experimenting.

The code that tries to break up the table name into parts and enclose the parts with ``[`` and ``]`` definitely doesn't work properly with 3 part (DB.schema.table) names.

When the collation is set in the DB (server or DB or object) to a case specific set (e.g. ``Latin1_General_CS_AS`` rather than ``Latin1_General_CI_AS`` -- ``CS` == case specific) then the ``name.toLowerCase()`` in ``NameNormaliser.normaliseName`` causes the issue.

I was thinking of simply changing ``dc.setString(1, normaliseName(objname));`` to ``dc.setString(1, objname);`` in ``SqlServerEnvironment.readIntoParams`` or normalising the name within this method without the case conversion.

There are existing broken SQL Server tests and the tests setup SQL script and the tests are not aligned in terms of object name cases so when I've tried creating the ``FitNesseTestDB" database with case sensitive collation then some of the tests are failing anyway. I'll try updating the SQL script and tests so that the object name cases are aligned then at least I'll be able to see if the code change is breaking anything else.

Some of the broken tests appear to be because the feature hasn't been implemented in the Java version (e.g. binary data type) but presumably was in the .Net version. I guess I can disable these tests. **Can you tell me how the disabled Oracle tests have been disabled so that I can try this too?**

**Comment by MMatten** [comment]
Aligning the tests to the setup SQL script (updating the table name in all fixture types and updating the column names in ``Query`` fixture queries) is all I've needed to do to get all of the tests (apart from those for unimplemented features) passing so it looks like there are no tricky changes required to ensure that row based fixtures don't have problems with mixed case column names.

**Comment by MMatten** [comment]
BTW it's also easy to get the whole `CoreTests` suite running against SQL Server so we could remove some of the specific/redundant tests at some point.

**Comment by javornikolov** [comment]
Hi @MMatten

> I'd like to pick this one up to resolve, via a PR, it as the forum post came from a user at my workplace.

Awesome :-)

> Can you tell me how the disabled Oracle tests have been disabled so that I can try this too?

This has been done by simply moving the tests to a "DisabledTests" suite. The build is invoking tests through JUnit - and only Flow* and Standlone* are invoked (DisabledTests is not).

**Comment by MMatten** [comment]
I'm thinking of dealing with this as a number of PRs from a single new branch. 
Firstly, disable the broken tests. Then fix the SQL Server issue, then migrate to the CoreTests suite. 

Or would you attack this as a single PR?

**Comment by javornikolov** [comment]
Separate PRs seems a better option to me.

**Comment by MMatten** [comment]
I think this one has now been resolved.

Might be good to open a new issue to sort out all of the disabled tests though.

**Comment by javornikolov** [comment]
OK, I'm closing this issue.
