### ISSUE TITLE
Explore possibility of migrating form Travis CI to Github Actions

### ISSUE THREAD

**Issue by javornikolov** [dbfit/dbfit#684]

**Comment by MMatten** [comment]
@javornikolov I've just checked in on the Travis CI credit limit. We have eaten 560 our of 35,000 build credits already. I think I've used had one build run from this allocation so I think our credits won't last long. Maybe our build VM setup is expensive because of all the databases we're installing. I'm not sure. But we might need to move to Github actions unless we can get regular top-ups from Travis.
