### ISSUE TITLE
Test execution hangs on an Apple chip M1 based laptop

### ISSUE THREAD

**Issue by forceedge01** [dbfit/dbfit#726]
Hello

We've encountered this on several new apple macs with the m1 chip - DbFit tests hang post execution of tests. This seems to be at the afterTests stage. We are not entirely sure but so far it has hanged indefinitely for us.

Do you need more information on this to look into this? Can this be simulated in any way to investigate / resolve the issue?

Thanks.

**Comment by javornikolov** [comment]
Hi, thanks for reporting this issue.

In order to isolate the issue, I am wondering whether it applies to [Fitnesse framework](http://docs.fitnesse.org) itself. If you create some simple FitNesse test independent of dbfit, do you experience the same issue?

Also - may you share the execution logs? E.g. from running a simple test like following: http://localhost:8085/DbFit.AcceptanceTests.JavaTests.HsqlTests.FlowMode.SimpleStoredProc?test

What is your java version?

**Comment by forceedge01** [comment]
Turns out, this was a deep rooted issue with the docker base image we were using. Switching to the ARM64 architecture solved the issue.
